modLoader="javafml" #mandatory
loaderVersion="[30,)"

issueTrackerURL="https://github.com/WTBW-Mods/WTBW_Core/issues/"

[[mods]]
modId="wtbw_core"
version="${file.jarVersion}"
displayName="WTBW Core"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="examplemod.png"
#credits="Thanks for this example mod goes to Java" #optional
authors="Naxanria, Sunekaer" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Core functionality and content for wtbw mods
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.wtbw_core]] #optional
    modId="forge"
    mandatory=true
    versionRange="[31.0.0,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.wtbw_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wtbw_core]]
    modId="wtbw_lib"
    mandatory=true
    versionRange="[1.0.13,)"
    ordering="NONE"
    side="BOTH"
